Try something

diff --git a/azure-cron.yml b/azure-cron.yml
--- a/azure-cron.yml
+++ b/azure-cron.yml
@@ -4,7 +4,14 @@
 # Azure Pipelines file, see https://aka.ms/yaml
 
 # Do not run on PRs
-pr: none
+# pr: none
+pr:
+  autoCancel: true # cancel previous builds on push
+  branches:
+    include:
+      - main
+      - main-2.x
+      - release/*
 
 # Do not run on merge to main
 trigger: none
@@ -28,97 +35,97 @@ trigger: none
 #  always: true
 
 jobs:
-  - job: fix_bazel_cache
-    timeoutInMinutes: 120
-    pool:
-      name: 'ubuntu_20_04'
-      demands: assignment -equals default
-    steps:
-      - checkout: self
-        clean: true
-      - bash: ci/dev-env-install.sh
-        displayName: 'Build/Install the Developer Environment'
-      - template: ci/bash-lib.yml
-        parameters:
-          var_name: bash-lib
-      - bash: |
-          set -euo pipefail
-          cd sdk
-          eval "$(dev-env/bin/dade assist)"
+  # - job: fix_bazel_cache
+  #   timeoutInMinutes: 120
+  #   pool:
+  #     name: 'ubuntu_20_04'
+  #     demands: assignment -equals default
+  #   steps:
+  #     - checkout: self
+  #       clean: true
+  #     - bash: ci/dev-env-install.sh
+  #       displayName: 'Build/Install the Developer Environment'
+  #     - template: ci/bash-lib.yml
+  #       parameters:
+  #         var_name: bash-lib
+  #     - bash: |
+  #         set -euo pipefail
+  #         cd sdk
+  #         eval "$(dev-env/bin/dade assist)"
 
-          bazel build //ci/cron:cron
+  #         bazel build //ci/cron:cron
 
-          key=$(mktemp)
-          cleanup="rm -rf $key ~/.config/gcloud"
-          trap "$cleanup" EXIT
-          echo "$GCRED" > $key
-          gcloud auth activate-service-account --key-file=$key
-          export BOTO_CONFIG=/dev/null
-          ./bazel-bin/ci/cron/cron bazel-cache --age 75 --delete --cache-suffix '**'
-        displayName: 'Fix Bazel Cache'
-        env:
-          GCRED: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
-      - template: ci/tell-slack-failed.yml
+  #         key=$(mktemp)
+  #         cleanup="rm -rf $key ~/.config/gcloud"
+  #         trap "$cleanup" EXIT
+  #         echo "$GCRED" > $key
+  #         gcloud auth activate-service-account --key-file=$key
+  #         export BOTO_CONFIG=/dev/null
+  #         ./bazel-bin/ci/cron/cron bazel-cache --age 75 --delete --cache-suffix '**'
+  #       displayName: 'Fix Bazel Cache'
+  #       env:
+  #         GCRED: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
+  #     - template: ci/tell-slack-failed.yml
 
-  - job: docker_image
-    timeoutInMinutes: 60
-    pool:
-      name: 'ubuntu_20_04'
-      demands: assignment -equals default
-    steps:
-      - checkout: self
-        clean: true
-      - bash: |
-          set -euo pipefail
+  # - job: docker_image
+  #   timeoutInMinutes: 60
+  #   pool:
+  #     name: 'ubuntu_20_04'
+  #     demands: assignment -equals default
+  #   steps:
+  #     - checkout: self
+  #       clean: true
+  #     - bash: |
+  #         set -euo pipefail
 
-          eval "$(cd sdk; dev-env/bin/dade-assist)"
-          cd sdk
+  #         eval "$(cd sdk; dev-env/bin/dade-assist)"
+  #         cd sdk
 
-          HEAD=$(git rev-parse HEAD)
-          while ! nix-build --no-out-link -A tools.sed -A tools.jq -A tools.curl -A tools.base64 nix; do :; done
+  #         HEAD=$(git rev-parse HEAD)
+  #         while ! nix-build --no-out-link -A tools.sed -A tools.jq -A tools.curl -A tools.base64 nix; do :; done
 
-          trap 'rm -rf ~/.docker' EXIT
-          echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
-          echo $DOCKER_CONTENT_TRUST_KEY | base64 -d > ~/.docker/da_automation.key
-          chmod 600 ~/.docker/da_automation.key
-          docker trust key load ~/.docker/da_automation.key --name $DOCKER_CONTENT_TRUST_USERNAME
+  #         trap 'rm -rf ~/.docker' EXIT
+  #         echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
+  #         echo $DOCKER_CONTENT_TRUST_KEY | base64 -d > ~/.docker/da_automation.key
+  #         chmod 600 ~/.docker/da_automation.key
+  #         docker trust key load ~/.docker/da_automation.key --name $DOCKER_CONTENT_TRUST_USERNAME
 
-          RELEASES=$(curl https://api.github.com/repos/digital-asset/daml/releases -sSfL | jq -r '.[] | .tag_name')
-          DIR=$(pwd)
-          VERSIONS=$(curl 'https://hub.docker.com/v2/repositories/digitalasset/daml-sdk/tags/?page_size=10000' -sSfL)
-          # Our docker tags should be stable. Therefore, we only build the image if it has not already
-          # been built before and we checkout the Dockerfile for the release tag.
-          # We do not update docker images for older releases so only docker images for SDK releases
-          # >= 0.13.43 are built this way.
-          for version in $(echo $RELEASES | sed -e 's/ /\n/g'); do
-            LAST_UPDATE=$(echo $VERSIONS | jq -r '.results[] | select(.name == "'${version#v}'") | .last_updated')
-            if [[ -n "$LAST_UPDATE" ]]; then
-              echo "${version#v} already exists, skipping."
-            else
-              echo "Building version ${version#v}..."
-              #git checkout "$version"
-              cd ci/docker/daml-sdk
-              docker build -t digitalasset/daml-sdk:${version#v} --build-arg VERSION=${version#v} .
-              #git checkout Dockerfile
-              # Despite the name not suggesting it at all, this actually signs
-              # _and pushes_ the image; see
-              # https://docs.docker.com/engine/security/trust/#signing-images-with-docker-content-trust
-              docker trust sign digitalasset/daml-sdk:${version#v}
-              cd "$DIR"
-              git checkout $HEAD
-              echo "Done."
-            fi
-          done
-        displayName: 'Build and Push Docker Image'
-        env:
-          DOCKER_LOGIN: $(DOCKER_LOGIN)
-          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
-          DOCKER_CONTENT_TRUST_KEY: $(DOCKER_CONTENT_TRUST_KEY)
-          DOCKER_CONTENT_TRUST_USERNAME: $(DOCKER_CONTENT_TRUST_USERNAME)
-          # Does not appear explicitly in the script, but is used by
-          # docker trust key load
-          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE)
-      - template: ci/tell-slack-failed.yml
+  #         RELEASES=$(curl https://api.github.com/repos/digital-asset/daml/releases -sSfL | jq -r '.[] | .tag_name')
+  #         DIR=$(pwd)
+  #         VERSIONS=$(curl 'https://hub.docker.com/v2/repositories/digitalasset/daml-sdk/tags/?page_size=10000' -sSfL)
+  #         # Our docker tags should be stable. Therefore, we only build the image if it has not already
+  #         # been built before and we checkout the Dockerfile for the release tag.
+  #         # We do not update docker images for older releases so only docker images for SDK releases
+  #         # >= 0.13.43 are built this way.
+  #         for version in $(echo $RELEASES | sed -e 's/ /\n/g'); do
+  #           LAST_UPDATE=$(echo $VERSIONS | jq -r '.results[] | select(.name == "'${version#v}'") | .last_updated')
+  #           if [[ -n "$LAST_UPDATE" ]]; then
+  #             echo "${version#v} already exists, skipping."
+  #           else
+  #             echo "Building version ${version#v}..."
+  #             #git checkout "$version"
+  #             cd ci/docker/daml-sdk
+  #             docker build -t digitalasset/daml-sdk:${version#v} --build-arg VERSION=${version#v} .
+  #             #git checkout Dockerfile
+  #             # Despite the name not suggesting it at all, this actually signs
+  #             # _and pushes_ the image; see
+  #             # https://docs.docker.com/engine/security/trust/#signing-images-with-docker-content-trust
+  #             docker trust sign digitalasset/daml-sdk:${version#v}
+  #             cd "$DIR"
+  #             git checkout $HEAD
+  #             echo "Done."
+  #           fi
+  #         done
+  #       displayName: 'Build and Push Docker Image'
+  #       env:
+  #         DOCKER_LOGIN: $(DOCKER_LOGIN)
+  #         DOCKER_PASSWORD: $(DOCKER_PASSWORD)
+  #         DOCKER_CONTENT_TRUST_KEY: $(DOCKER_CONTENT_TRUST_KEY)
+  #         DOCKER_CONTENT_TRUST_USERNAME: $(DOCKER_CONTENT_TRUST_USERNAME)
+  #         # Does not appear explicitly in the script, but is used by
+  #         # docker trust key load
+  #         DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE)
+  #     - template: ci/tell-slack-failed.yml
 
   - job: vscode_marketplace
     timeoutInMinutes: 10
@@ -169,7 +176,7 @@ jobs:
                               | .[0]
                               | map(tostring)
                               | join(".")')
-          if [[ "$GITHUB" != "$MARKET" ]] && git merge-base --is-ancestor 798e96c9b9034eac85ace786b9e1955cf380285c v$GITHUB; then
+          # if [[ "$GITHUB" != "$MARKET" ]] && git merge-base --is-ancestor 798e96c9b9034eac85ace786b9e1955cf380285c v$GITHUB; then
             echo "Publishing $GITHUB to VSCode Marketplace"
             git checkout v$GITHUB
             (
@@ -183,47 +190,47 @@ jobs:
             # This produces out/src/extension.js
             bazel run --run_under="cd $PWD &&" @yarn//:yarn install
             bazel run --run_under="cd $PWD &&" @yarn//:yarn compile
-            bazel run --run_under="cd $PWD &&" @daml_extension_deps//vsce/bin:vsce -- publish --yarn $GITHUB -p $MARKETPLACE_TOKEN
+            bazel run --run_under='cd $BUILD_WORKING_DIRECTORY &&' @daml_extension_deps//vsce/bin:vsce -- package --yarn
             )
-          else
-            if [[ "$GITHUB" == "$MARKET" ]]; then
-              echo "Version on marketplace is already the latest ($GITHUB)."
-            else
-              echo "Latest version is not ready for marketplace publication."
-            fi
-          fi
+          # else
+          #   if [[ "$GITHUB" == "$MARKET" ]]; then
+          #     echo "Version on marketplace is already the latest ($GITHUB)."
+          #   else
+          #     echo "Latest version is not ready for marketplace publication."
+          #   fi
+          # fi
         displayName: 'Publish to VSCode Marketplace'
         env:
           MARKETPLACE_TOKEN: $(VSCODE_MARKETPLACE_TOKEN)
       - template: ci/tell-slack-failed.yml
 
-  - job: download_stats
-    timeoutInMinutes: 10
-    pool:
-      name: "ubuntu_20_04"
-      demands: assignment -equals default
-    steps:
-      - checkout: self
-        clean: true
-      - bash: |
-          set -euo pipefail
+  # - job: download_stats
+  #   timeoutInMinutes: 10
+  #   pool:
+  #     name: "ubuntu_20_04"
+  #     demands: assignment -equals default
+  #   steps:
+  #     - checkout: self
+  #       clean: true
+  #     - bash: |
+  #         set -euo pipefail
 
-          eval "$(cd sdk; dev-env/bin/dade-assist)"
+  #         eval "$(cd sdk; dev-env/bin/dade-assist)"
 
-          STATS=$(mktemp)
-          curl https://api.github.com/repos/digital-asset/daml/releases -sSfL | gzip -9 > $STATS
+  #         STATS=$(mktemp)
+  #         curl https://api.github.com/repos/digital-asset/daml/releases -sSfL | gzip -9 > $STATS
 
-          GCS_KEY=$(mktemp)
-          cleanup () {
-              rm -f $GCS_KEY
-          }
-          trap cleanup EXIT
-          echo "$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > $GCS_KEY
-          gcloud auth activate-service-account --key-file=$GCS_KEY
-          BOTO_CONFIG=/dev/null gsutil cp $STATS gs://daml-data/downloads/$(date -u +%Y%m%d_%H%M%SZ).json.gz
-        displayName: 'Download Stats'
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
-      - template: ci/tell-slack-failed.yml
+  #         GCS_KEY=$(mktemp)
+  #         cleanup () {
+  #             rm -f $GCS_KEY
+  #         }
+  #         trap cleanup EXIT
+  #         echo "$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > $GCS_KEY
+  #         gcloud auth activate-service-account --key-file=$GCS_KEY
+  #         BOTO_CONFIG=/dev/null gsutil cp $STATS gs://daml-data/downloads/$(date -u +%Y%m%d_%H%M%SZ).json.gz
+  #       displayName: 'Download Stats'
+  #       env:
+  #         GOOGLE_APPLICATION_CREDENTIALS_CONTENT: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
+  #     - template: ci/tell-slack-failed.yml
 
-  - template: ci/refresh-get-daml-com.yml
+  # - template: ci/refresh-get-daml-com.yml
