.

diff --git a/ci/cron/daily-compat.yml b/ci/cron/daily-compat.yml
--- a/ci/cron/daily-compat.yml
+++ b/ci/cron/daily-compat.yml
@@ -226,45 +226,45 @@ jobs:
 
           bazel build //...
           # Make sure that Bazel query works
-          bazel query 'deps(//...)'
+          bazel query 'deps(//...)' >/dev/null
         displayName: 'Build'
-      - bash: |
-          set -euo pipefail
-          eval "$(./dev-env/bin/dade-assist)"
-          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
-          ci-build digital-asset_daml master \
-          --logging.level.com.synopsys.integration=DEBUG \
-          --detect.tools=BAZEL \
-          --detect.bazel.target=//... \
-          --detect.bazel.dependency.type=haskell_cabal_library \
-          --detect.notices.report=true \
-          --detect.report.timeout=1500
-        displayName: 'Blackduck Haskell Scan'
-        env:
-          BLACKDUCK_HUBDETECT_TOKEN: $(BLACKDUCK_HUBDETECT_TOKEN)
-      - bash: |
-          set -euo pipefail
-          eval "$(./dev-env/bin/dade-assist)"
-          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
-          ci-build digital-asset_daml master \
-          --logging.level.com.synopsys.integration=DEBUG \
-          --detect.npm.include.dev.dependencies=false \
-          --detect.excluded.detector.types=NUGET \
-          --detect.excluded.detector.types=GO_MOD \
-          --detect.yarn.prod.only=true \
-          --detect.python.python3=true \
-          --detect.tools=DETECTOR,BAZEL,DOCKER \
-          --detect.bazel.target=//... \
-          --detect.bazel.dependency.type=maven_install \
-          --detect.detector.search.exclusion.paths=language-support/ts/codegen/tests/ts,language-support/ts,language-support/scala/examples/iou-no-codegen,language-support/scala/examples/quickstart-scala,docs/source/app-dev/bindings-java/code-snippets,docs/source/app-dev/bindings-java/quickstart/template-root,language-support/scala/examples/quickstart-scala,language-support/scala/examples/iou-no-codegen \
-          --detect.cleanup=false \
-          --detect.policy.check.fail.on.severities=MAJOR,CRITICAL,BLOCKER \
-          --detect.notices.report=true \
-          --detect.cleanup.bdio.files=true \
-          --detect.report.timeout=4500
-        displayName: 'Blackduck Scan'
-        env:
-          BLACKDUCK_HUBDETECT_TOKEN: $(BLACKDUCK_HUBDETECT_TOKEN)
+          #- bash: |
+          #    set -euo pipefail
+          #    eval "$(./dev-env/bin/dade-assist)"
+          #    bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
+          #    ci-build digital-asset_daml master \
+          #    --logging.level.com.synopsys.integration=DEBUG \
+          #    --detect.tools=BAZEL \
+          #    --detect.bazel.target=//... \
+          #    --detect.bazel.dependency.type=haskell_cabal_library \
+          #    --detect.notices.report=true \
+          #    --detect.report.timeout=1500
+          #  displayName: 'Blackduck Haskell Scan'
+          #  env:
+          #    BLACKDUCK_HUBDETECT_TOKEN: $(BLACKDUCK_HUBDETECT_TOKEN)
+          #- bash: |
+          #    set -euo pipefail
+          #    eval "$(./dev-env/bin/dade-assist)"
+          #    bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
+          #    ci-build digital-asset_daml master \
+          #    --logging.level.com.synopsys.integration=DEBUG \
+          #    --detect.npm.include.dev.dependencies=false \
+          #    --detect.excluded.detector.types=NUGET \
+          #    --detect.excluded.detector.types=GO_MOD \
+          #    --detect.yarn.prod.only=true \
+          #    --detect.python.python3=true \
+          #    --detect.tools=DETECTOR,BAZEL,DOCKER \
+          #    --detect.bazel.target=//... \
+          #    --detect.bazel.dependency.type=maven_install \
+          #    --detect.detector.search.exclusion.paths=language-support/ts/codegen/tests/ts,language-support/ts,language-support/scala/examples/iou-no-codegen,language-support/scala/examples/quickstart-scala,docs/source/app-dev/bindings-java/code-snippets,docs/source/app-dev/bindings-java/quickstart/template-root,language-support/scala/examples/quickstart-scala,language-support/scala/examples/iou-no-codegen \
+          #    --detect.cleanup=false \
+          #    --detect.policy.check.fail.on.severities=MAJOR,CRITICAL,BLOCKER \
+          #    --detect.notices.report=true \
+          #    --detect.cleanup.bdio.files=true \
+          #    --detect.report.timeout=4500
+          #  displayName: 'Blackduck Scan'
+          #  env:
+          #    BLACKDUCK_HUBDETECT_TOKEN: $(BLACKDUCK_HUBDETECT_TOKEN)
       - template: ../bash-lib.yml
         parameters:
           var_name: bash_lib
@@ -273,7 +273,8 @@ jobs:
           eval "$(./dev-env/bin/dade-assist)"
           source $(bash_lib)
 
-          tr -d '\015' <*_Black_Duck_Notices_Report.txt | grep -v dach-ny_daml-on-corda >NOTICES
+          sed -i 1d NOTICES
+          #tr -d '\015' <*_Black_Duck_Notices_Report.txt | grep -v dach-ny_daml-on-corda >NOTICES
           if git diff --exit-code -- NOTICES; then
               echo "NOTICES file already up-to-date."
           else
