clean-up perf tests (#10355)
We've removed some features, this can be simplified a bit now.

CHANGELOG_BEGIN
CHANGELOG_END

diff --git a/ci/cron/daily-compat.yml b/ci/cron/daily-compat.yml
--- a/ci/cron/daily-compat.yml
+++ b/ci/cron/daily-compat.yml
@@ -90,17 +90,21 @@ jobs:
           eval "$(dev-env/bin/dade assist)"
           source $(bash_lib)
 
-          OUT="$(Build.StagingDirectory)/perf-results.json"
+          OUT="$(Build.StagingDirectory)/perf-results-speedy.json"
 
-          START=$(date -u +%Y%m%d_%H%M%SZ)
+          START=$(git log -n1 --format=%cd --date=format:%Y%m%d).$(git rev-list --count HEAD).$(Build.BuildId).$(git log -n1 --format=%h --abbrev=8)
 
-          ci/cron/perf/bench.sh > "$OUT"
-
-          cat $OUT
+          tmp=$(mktemp -d)/out.json
+          bazel run daml-lf/scenario-interpreter:scenario-perf -- -rf json -rff $tmp >&2
+          perf=$(printf '%.2f' $(cat $tmp | jq '.[0].primaryMetric.score'))
+          if [ "" = "$perf" ]; then exit 1; fi
+          sha=$(git rev-parse HEAD)
+          echo '{"current-perf": '$perf', "current-sha": "'$sha'"}' > "$OUT"
+          cat "$OUT"
 
           gcs "$GCRED" cp "$OUT" gs://daml-data/perf/speedy/$START.json
 
-          setvar speedy_perf "$(jq -r '."current-perf"' "$OUT")"
+          setvar speedy_perf "$perf"
 
         displayName: measure perf
         name: out
@@ -108,8 +112,8 @@ jobs:
           GCRED: $(GOOGLE_APPLICATION_CREDENTIALS_CONTENT)
       - task: PublishPipelineArtifact@0
         inputs:
-          targetPath: $(Build.StagingDirectory)/perf-results.json
-          artifactName: perf
+          targetPath: $(Build.StagingDirectory)/perf-results-speedy.json
+          artifactName: perf-speedy
 
   - job: perf_http_json
     timeoutInMinutes: 120
@@ -347,7 +351,12 @@ jobs:
            && "$(check_releases)" == "Succeeded"
            && ("$(blackduck_scan)" == "Succeeded" || "$(blackduck_scan)" == "Skipped")
            && ("$(run_notices_pr_build)" == "Succeeded" || "$(run_notices_pr_build)" == "Skipped") ]]; then
-            tell_slack "Daily tests passed: $COMMIT_LINK (speedy_perf: $(speedy_perf))." "$(Slack.ci-failures-daml)"
+            MSG="Daily tests passed: $COMMIT_LINK"
+            REPORT='```
+        speedy_perf: $(speedy_perf)
+        ```
+        '
+            tell_slack "$(echo -e "$MSG\n$REPORT")" "$(Slack.ci-failures-daml)"
         else
             tell_slack "Daily tests failed: $COMMIT_LINK." "$(Slack.ci-failures-daml)"
         fi
