Build canton OCI locally, grab dpm through bazel, update dpm-sdk-head

diff --git a/sdk/dev-env/bin/dpm-sdk-head b/sdk/dev-env/bin/dpm-sdk-head
--- a/sdk/dev-env/bin/dpm-sdk-head
+++ b/sdk/dev-env/bin/dpm-sdk-head
@@ -14,16 +14,18 @@ BAZEL_MODE_FLAGS=()
 COMPONENT_VERSION=0.0.0
 RELEASE_VERSION=0.0.0
 TO_BUILD=()
+TO_SKIP=()
 NUKE=0
-SKIP_JARS=0
-REFRESH_EXTERNAL=0
 PROFILING=0
-REMOVE_NON_HEAD=0
+REMOVE_OTHER_VERSIONS=0
 VERBOSE=0
 # 0 = no message, 1 = add path instructions, 2 = reload shell
 LOG_PATH_INSTRUCTIONS=0
 for opt in "$@"; do
   case "$opt" in
+    --canton-community)
+      TO_BUILD+=(canton-community)
+      ;;
     --damlc)
       TO_BUILD+=(damlc)
       ;;
@@ -42,6 +44,12 @@ for opt in "$@"; do
     --dpm)
       TO_BUILD+=(dpm)
       ;;
+    --jars)
+      TO_BUILD+=(jars)
+      ;;
+    --skip-*)
+      TO_SKIP+=${opt#--skip-}
+      ;;
     --version=*)
       RELEASE_VERSION=${opt#--version=}
       COMPONENT_VERSION=${opt#--version=}
@@ -58,21 +66,18 @@ for opt in "$@"; do
     --nuke)
       NUKE=1
       ;;
-    --skip-jars)
-      SKIP_JARS=1
-      ;;
-    --refresh-external)
-      REFRESH_EXTERNAL=1
-      ;;
-    --remove-non-head)
-      REMOVE_NON_HEAD=1
+    --remove-other-versions)
+      REMOVE_OTHER_VERSIONS=1
       ;;
     --verbose)
+      ;&
+    -v)
       VERBOSE=1
       ;;
     *)
       echo "Unknown option: $opt"
       echo "Available options:"
+      echo "  --canton-community Build and update the canton-community component"
       echo "  --damlc Build and update the damlc component"
       echo "  --daml-script Build and update the daml-script component"
       echo "  --codegen Build and update the codegen component"
@@ -83,32 +88,14 @@ for opt in "$@"; do
       echo "  --component-version=<version> Set the component version (internal to dpm) to be built, default 0.0.0"
       echo "  --release-version=<version> Set the release version (sdk-version in daml.yaml) to contain built components, default 0.0.0"
       echo "  --profiling Build Haskell executables with profiling enabled"
-      echo "  --nuke Remove DPM from your system entirely (does not build anything)"
-      echo "  --skip-jars  Skip building and installing the JARs."
-      echo "  --refresh-external Remove DPM and reinstall from latest public before building components"
-      echo "  --remove-non-head After installing head, remove all other installed versions (assemblies only, components remain, this will not save disk space)"
+      echo "  --nuke Remove DPM from your system entirely before building"
+      echo "  --skip-* Skip building and installing a component, such as `--skip-jars`"
+      echo "  --remove-other-versions After installing head, remove all other installed versions (assemblies only, components remain, this will not save disk space)"
       echo "  --verbose Print bazel build logs as they build live"
 
       exit 1
   esac
 done
-
-# Ensure `gcloud auth login` has been run
-if [ -z "$(gcloud config list account --format 'value(core.account)')" ]; then
-  echo "$(tput setaf 1)GCloud reports no auth accounts, you must authenticate with gcloud to pull down DPM.$(tput sgr 0)"
-  echo "Please run the following:"
-  echo "gcloud auth login"
-  echo "gcloud auth configure-docker europe-docker.pkg.dev"
-  exit 1
-fi
-
-# Ensure `gcloud auth configure-docker europe-docker.pkg.dev` has been run
-if [ ! -f "$HOME/.docker/config.json" ] || grep -zqv europe-docker.pkg.dev "$HOME/.docker/config.json"; then
-  echo "$(tput setaf 1)GCloud docker configuration is missing (you do not need to install docker).$(tput sgr 0)"
-  echo "Please run the following:"
-  echo "gcloud auth configure-docker europe-docker.pkg.dev"
-  exit 1
-fi
 
 if [[ "$PROFILING" -ne 0 ]]; then
   BAZEL_MODE_FLAGS+=(-c dbg)
@@ -116,15 +103,27 @@ fi
 
 readonly DPM_HOME="$HOME/.dpm"
 
-if [[ "$NUKE" -ne 0 || "$REFRESH_EXTERNAL" -ne 0 ]]; then
+if [[ "$NUKE" -ne 0 ]]; then
   rm -rf "$DPM_HOME"
   echo "$(tput setaf 3)Removed DPM from system.$(tput sgr 0)"
-  if [[ "$NUKE" -ne 0 ]]; then exit; fi
 fi
 
+get_dpm() {
+  bazel build @dpm_binary//:dpm
+  dpm_bazel_path=$(bazel cquery "${BAZEL_MODE_FLAGS[@]}" "@dpm_binary//:dpm" --output=files 2> /dev/null)
+  dpm_version=$(HOME=. $dpm_bazel_path -v 2> /dev/null | head -n 1 | sed -e "s/^version: //")
+  mkdir -p "$DPM_HOME/cache/components/dpm/${dpm_version}" "$DPM_HOME/bin" "$DPM_HOME/cache/sdk/open-source"
+  cp $dpm_bazel_path "$DPM_HOME/cache/components/dpm/${dpm_version}/dpm"
+  # Create symlink for .dpm/bin, to match DPM's current behaviour
+  ln -sf "${DPM_HOME}/cache/components/dpm/${dpm_version}/dpm" "${DPM_HOME}/bin/dpm"
+  echo $dpm_version
+}
+
 if [ ! -d "$DPM_HOME" ]; then
-  echo "$(tput setaf 5)DPM is not installed, installing latest from remote....$(tput sgr 0)"
-  "$REPO_ROOT/../ci/get-dpm.sh" "europe-docker.pkg.dev/da-images/public-unstable/components/dpm:latest"
+  echo "$(tput setaf 5)DPM is not installed, installing from bazel...$(tput sgr 0)"
+
+  get_dpm
+
   cat > "${DPM_HOME}/dpm-config.yaml" << EOF
 edition: open-source
 registry: europe-docker.pkg.dev/da-images/public-unstable
@@ -164,6 +163,8 @@ EOF
     fi
   fi
   echo "$(tput setaf 3)DPM installed.$(tput sgr 0)"
+  # Don't need to update DPM if we just grabbed it
+  TO_SKIP+=(dpm)
 fi
 
 # Some issues with updating release yaml file
@@ -171,33 +172,40 @@ chmod -R u+w "$DPM_HOME"
 
 assembly_location="$DPM_HOME/cache/sdk/open-source/$RELEASE_VERSION.yaml"
 
-# When installing via `get-dpm`, an SDK is not installed
-# Detect this and install open-source latest
-if [ -z "$(find "$DPM_HOME"/cache/sdk/* -type f)" ]; then
-  echo "$(tput setaf 5)No assemblies installed for copying from, installing latest.$(tput sgr 0)"
-  "$DPM_HOME/bin/dpm" install latest
-  echo "$(tput setaf 3)Installed $("$DPM_HOME/bin/dpm" versions -o json | jq -r '.[] | select(.active==true).version').$(tput sgr 0)"
-fi
+all_dpm_components=(canton-community damlc daml-script codegen daml-new upgrade-check)
 
-# Create a `$RELEASE_VERSION.yaml` by copying the current latest installed version and updating the name/version field
+# Create a `RELEASE_VERSION.yaml` if it doesn't exist already with only daml components
 if [ ! -f "$assembly_location" ]; then
-  echo "$(tput setaf 5)No assembly found for $RELEASE_VERSION, creating new.$(tput sgr 0)"
-  latest_version=$("$DPM_HOME/bin/dpm" versions -o json | jq -r '.[] | select(.active==true).version')
   assembly_location="$DPM_HOME/cache/sdk/open-source/$RELEASE_VERSION.yaml"
-  cp "$DPM_HOME/cache/sdk/open-source/${latest_version}.yaml" "$assembly_location"
-  # yq has trouble picking up env vars
-  RELEASE_VERSION=$RELEASE_VERSION yq -MiY '.spec.version |= env.RELEASE_VERSION' "$assembly_location"
-  echo "$(tput setaf 3)Created assembly for $RELEASE_VERSION from ${latest_version}.$(tput sgr 0)"
+  dpm_version=$(HOME=. $DPM_HOME/bin/dpm -v 2> /dev/null | head -n 1 | sed -e "s/^version: //")
+
+  component_versions=""
+  # Macos got angry with value loops, so looping keys
+  for i in "${!all_dpm_components[@]}"; do
+    component_versions="$component_versions${all_dpm_components[$i]}:
+      version: $COMPONENT_VERSION
+    "
+  done
+
+  cat > "$assembly_location" << EOF
+apiVersion: digitalasset.com/v1
+kind: SdkManifest
+spec:
+  components:
+    $component_versions
+  assistant:
+    version: $dpm_version
+  version: $RELEASE_VERSION
+  edition: open-source
+EOF
+  echo "$(tput setaf 3)Created assembly for $RELEASE_VERSION.$(tput sgr 0)"
 fi
 
-all_components=(damlc daml-script codegen daml-new upgrade-check)
+all_components=("${all_dpm_components[@]}" jars dpm)
 
 # If no explicit components specified, update all
 if [[ ! ${TO_BUILD[@]} ]]; then
   TO_BUILD=("${all_components[@]}")
-else
-  # If an explicit component is given, skip jars
-  SKIP_JARS=1
 fi
 
 # Imitate `chronic` from coreutils
@@ -222,19 +230,35 @@ chronic() {
 update_component() {
   target_name=$1
   progress_marker=$2
+
   if [[ "$target_name" = "dpm" ]]; then
     # For DPM, we pull down from OCI again
     echo "$(tput setaf 5)$progress_marker Pulling down new DPM binary.$(tput sgr 0)"
 
-    # get-dpm script doesn't delete, it only updates
-    # use it to pull down a new dpm
-    "$REPO_ROOT/../ci/get-dpm.sh" "europe-docker.pkg.dev/da-images/public-unstable/components/dpm:latest"
-    version_line=$("$DPM_HOME/bin/dpm" --version | grep -o 'version: .*')
-    DPM_VERSION=${version_line#version: }
+    DPM_VERSION=$(get_dpm)
 
     # Update our $RELEASE_VERSION.yaml to point to new DPM
     DPM_VERSION=$DPM_VERSION yq -MiY '.spec.assistant.version |= env.DPM_VERSION' "$assembly_location"
     echo "$(tput setaf 3)$progress_marker Installed most recent dpm.$(tput sgr 0)"
+  elif [[ "$target_name" = "jars" ]]; then
+    tmp="$(mktemp -d)"
+    
+    function cleanup() {
+      echo "$(tput setaf 3)FAILED TO INSTALL JARS! $(tput sgr 0)"
+      rm -rf $tmp
+    }
+    trap cleanup EXIT
+
+    echo "$(tput setaf 5)$progress_marker Building //release:release for JARs.$(tput sgr 0)"
+    bazel build ${BAZEL_MODE_FLAGS[@]:-} //release:release
+    RELEASE_ARGS=(--release-dir "$tmp" --install-head-jars --no-ts --no-docs)
+    echo "$(tput setaf 5)$progress_marker Built //release:release, running...$(tput sgr 0)"
+
+    DAML_SDK_RELEASE_VERSION=$COMPONENT_VERSION "${REPO_ROOT}/bazel-bin/release/release" ${RELEASE_ARGS[@]}
+    rm -rf $tmp
+    trap - EXIT
+
+    echo "$(tput setaf 3)$progress_marker Installed JARs.$(tput sgr 0)"
   else
     # Find the OCI bazel target for the component as `package_oci_component` rule named `${component}-oci`
     bazel_path=$(bazel query "kind('package_oci_component', //...)" 2> /dev/null | grep "$target_name-oci")
@@ -245,6 +269,7 @@ update_component() {
     # Find built tar and unpack to DPM component
     output_path=$(bazel cquery "${BAZEL_MODE_FLAGS[@]}" "$bazel_path" --output=files 2> /dev/null)
     component_path="$DPM_HOME/cache/components/$target_name/$COMPONENT_VERSION"
+    rm -rf $component_path
     mkdir -p "$component_path"
     tar -xzf "$output_path" -C "$component_path"
     echo "$(tput setaf 5)$progress_marker Unpacked component, updating assembly.$(tput sgr 0)"
@@ -254,41 +279,32 @@ update_component() {
   fi
 }
 
+# Remove the components to be skipped by rebuilding the list
+# bash makes this painful :(
+unskipped_to_build=("${TO_BUILD[@]}")
+TO_BUILD=()
+for i in "${!unskipped_to_build[@]}"; do
+  if [[ ! " ${TO_SKIP[*]} " =~ [[:space:]]${unskipped_to_build[$i]}[[:space:]] ]]; then
+    TO_BUILD+=("${unskipped_to_build[$i]}")
+  fi
+done
+
 for i in "${!TO_BUILD[@]}"; do
   update_component "${TO_BUILD[$i]}" "($((i + 1))/${#TO_BUILD[@]})"
 done
 
-# TODO: Implement fully once DPM supports this, See https://github.com/DACH-NY/dpm/issues/421
-# cat > "${DPM_HOME}/bin/dpm-head" << EOF
-# #!/bin/sh
-# exec env DAML_SDK_VERSION=$DAML_SDK_RELEASE_VERSION "${DPM_HOME}/cache/components/dpm/$COMPONENT_VERSION/dpm" "\$@"
-# EOF
-# chmod +x "${DPM_HEAD}/bin/dpm-head"
+#dpm-head script which overrides the sdk version to 0.0.0 (since default is highest)
+cat > "${DPM_HOME}/bin/dpm-head" << EOF
+#!/bin/sh
+exec env DPM_SDK_VERSION=$RELEASE_VERSION "${DPM_HOME}/bin/dpm" "\$@"
+EOF
+chmod +x "${DPM_HOME}/bin/dpm-head"
+echo "$(tput setaf 3)Updated dpm-head to point to $RELEASE_VERSION.$(tput sgr 0)"
 
-if [[ $REMOVE_NON_HEAD -ne 0 ]]; then
+if [[ $REMOVE_OTHER_VERSIONS -ne 0 ]]; then
   # Deleting sdk/* rather than sdk with a depth of 2, to avoid accidentally deleting sdk/.lock
   find "$DPM_HOME"/cache/sdk/* ! -name "$RELEASE_VERSION.yaml" -type f -exec rm -f {} +
   echo "$(tput setaf 1)Removed all versions other than $RELEASE_VERSION$(tput sgr 0)"
-fi
-
-if [[ $SKIP_JARS -eq 0 ]]; then
-    echo "$(tput setaf 3)Installing JARs as $COMPONENT_VERSION...$(tput sgr 0)"
-    tmp="$(mktemp -d)"
-    
-    function cleanup() {
-      echo "$(tput setaf 3)FAILED TO INSTALL JARS! $(tput sgr 0)"
-      rm -rf $tmp
-    }
-    trap cleanup EXIT
-
-    bazel build ${BAZEL_MODE_FLAGS[@]:-} //release:release
-    RELEASE_ARGS=(--release-dir "$tmp" --install-head-jars --no-ts --no-docs)
-
-    DAML_SDK_RELEASE_VERSION=$COMPONENT_VERSION "${REPO_ROOT}/bazel-bin/release/release" ${RELEASE_ARGS[@]}
-    rm -rf $tmp
-    trap - EXIT
-
-    echo "$(tput setaf 3)Done installing JARs as $COMPONENT_VERSION.$(tput sgr 0)"
 fi
 
 echo "$(tput setaf 2)Installed $RELEASE_VERSION to dpm.$(tput sgr 0)"
