Log commands in the check-for-release step (#21210)
* Log commands in the check-for-release step

* try to disable -x to see if it fixes the CI

* try to -x on stdout

* display on stdout at the end

* trap errors and only displays failing line

diff --git a/ci/check-for-release-job.yml b/ci/check-for-release-job.yml
--- a/ci/check-for-release-job.yml
+++ b/ci/check-for-release-job.yml
@@ -17,6 +17,15 @@ jobs:
         var_name: bash-lib
     - bash: |
         set -euo pipefail
+        
+        error_handler() {
+          local exit_code="$1"
+          local line_number="$2"
+          local command="$3"
+          echo "Error: Command '$command' on line $line_number exited with status $exit_code" >&2
+        }
+        trap 'error_handler $? $LINENO "$BASH_COMMAND"' ERR 
+        
         cd sdk
         eval "$(./dev-env/bin/dade-assist)"
         source $(bash-lib)
